title = "OWASP Juice Shop DevSecOps Configuration"

##############################################################
# Allowlist
##############################################################

[allowlist]

description = "Allow test/demo secrets used for Semgrep demonstrations"

paths = [
    '''test/.*''',
    '''docs/.*'''
]

##############################################################
# Ignore Rules
##############################################################

regexes = [
    '''changeme''',
    '''dummy''',
    '''test123''',
    '''password123'''
]

##############################################################
# Entropy
##############################################################

entropy = 3.5