###############################################################
# Stage 1 - Build
###############################################################
FROM node:24-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

###############################################################
# Stage 2 - Runtime
###############################################################
FROM node:24-alpine

WORKDIR /app

RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup

COPY --from=builder /app /app

RUN chown -R appuser:appgroup /app

USER appuser

ENV NODE_ENV=production

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
CMD wget --quiet --tries=1 --spider http://localhost:3000 || exit 1

CMD ["npm", "start"]