name: DevSecOps Pipeline

###########################################################
# Trigger Pipeline
###########################################################
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

###########################################################
# Global Environment Variables
###########################################################
env:
  NODE_VERSION: "24"
  IMAGE_NAME: juice-shop-secure

###########################################################
# Job 1 - Build Application
###########################################################
jobs:

  build:

    name: Build Application

    runs-on: ubuntu-latest

    steps:

      #####################################################
      # Checkout Repository
      #####################################################

      - name: Checkout Source
        uses: actions/checkout@v4

      #####################################################
      # Install Node
      #####################################################

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: npm

      #####################################################
      # Install Dependencies
      #####################################################

      - name: Install Dependencies
        run: npm install

      #####################################################
      # Build Application
      #####################################################

      - name: Build Juice Shop
        run: npm run build

###########################################################
# Job 2 - Secret Scanning
###########################################################

  gitleaks:

    name: Secret Scanning

    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v4

      #####################################################
      # Scan for Secrets
      #####################################################

      - name: Run Gitleaks

        uses: gitleaks/gitleaks-action@v2

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

###########################################################
# Job 3 - SAST (Semgrep)
###########################################################

  semgrep:

    name: Static Application Security Testing

    runs-on: ubuntu-latest

    needs: build

    container:

      image: semgrep/semgrep:1.92.0

    steps:

      - uses: actions/checkout@v4

      #####################################################
      # Run Semgrep
      #####################################################

      - name: Run Semgrep

        run: |

          semgrep scan \
          --config auto \
          --config .semgrep/custom-rules.yml \
          --severity ERROR \
          --sarif \
          --output semgrep.sarif \
          

      #####################################################
      # Upload Report
      #####################################################

      - name: Upload SARIF

        uses: actions/upload-artifact@v4

        with:

          name: semgrep-report

          path: semgrep.sarif

###########################################################
# Job 4 - SCA + SBOM
###########################################################

  sca:

    name: Dependency Scan + SBOM

    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v4

      #####################################################
      # Generate CycloneDX SBOM
      #####################################################

      - name: Generate SBOM

        uses: anchore/sbom-action@v0

        with:

          format: cyclonedx-json

          output-file: sbom.cdx.json

      #####################################################
      # Upload SBOM
      #####################################################

      - name: Upload SBOM

        uses: actions/upload-artifact@v4

        with:

          name: CycloneDX-SBOM

          path: sbom.cdx.json

      #####################################################
      # Filesystem Scan
      #####################################################

      - name: Trivy Dependency Scan

        uses: aquasecurity/trivy-action@master

        with:

          scan-type: fs

          scan-ref: .

          severity: HIGH,CRITICAL

          ignore-unfixed: true

          exit-code: 0

          format: table

###########################################################
# Job 5 - Docker Build
###########################################################

  docker:

    name: Hardened Docker Build

    runs-on: ubuntu-latest

    needs:

      - gitleaks

      - semgrep

      - sca

    steps:

      - uses: actions/checkout@v4

      #####################################################
      # Build Hardened Image
      #####################################################

      - name: Build Docker Image

        run: |

          docker build \
          -f Dockerfile.hardened \
          -t $IMAGE_NAME:latest .

###########################################################
# Job 6 - Container Scan
###########################################################

  container:

    name: Container Security Scan

    runs-on: ubuntu-latest

    needs: docker

    steps:

      - name: Scan Docker Image

        uses: aquasecurity/trivy-action@master

        with:

          image-ref: ${{ env.IMAGE_NAME }}:latest

          severity: HIGH,CRITICAL

          ignore-unfixed: true

          exit-code: 0

          format: table